### ISSUE TITLE
When targeting HomePod - volume increases before pausing media

### ISSUE THREAD

**Issue by JonLaliberte** [nimroddolev/chime_tts#12] opened 2023-08-15 13:09 UTC
## System Information

version | core-2023.8.2
host_os | Home Assistant OS 10.4

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

HomePod volume increased as soon as the service call executed, but before the currently playing media paused.

### Reproduction steps

1. Target a HomePod
2. Call the chime_tts.say service, setting the volume to something different from the current setting.
3. Observe
...

### Debug logs

```text
NA
```

**Comment by JonLaliberte** [comment] 2023-08-15 20:37
Ok. I was playing with this again just now targeting a different HomePod (and UniFi doorbell) and it was working great.
I added the office HomePod to it again this time it worked!

I noticed that I do need to select Entities, that if I try selecting Devices it will fail.

I'm wondering if something is up with the HomePod (via AppleTV integration) where if there is currently a stream (AirPlay from Mac in this case), that it causes problems taking it over.

**Comment by nimroddolev** [comment] 2023-08-15 20:51
I think the issue with the volume being changed too early actually has to do with a delay that happens between initiating playback on the HomePod Mini, to when it _actually_ starts playing.

More specifically: The `volume_set` service is called on the HomePod right before the `play_media` service (which has the delay), so the volume is changed but then there's a delay from when the HomePod prepares to play the audio to when the audio is played.

I think this delay is likely asynchronous and likely to be different each time the HomePod Mini plays Chime TTS audio (or any other audio from Home Assistant). I don't receive any feedback telling me when the audio _actually_ starts playing so I can't know when to change the volume so it coincides with the start of playback.

I don't think I can fix this issue as it looks like a hardware limitation for how the HomePod streams audio from Home Assistant. Unfortunately I can currently only come up with a compromise solution of

1. Pausing any current media on the HomePod Mini
2. Adjusting the volume
3. Playing the Chime TTS audio
4. Restoring the volume

I am not sure I can then resume the previously playing audio. I need to look into it further. I'll post an update here once I know more.

**Comment by JonLaliberte** [comment] 2023-08-15 21:12
Yeah, what I've done in my current automations is basically what you've described.
It's not the best solution, but given the options currently provided I think it's the only way.

**Comment by nimroddolev** [comment] 2023-08-17 08:39
The issue raised is not caused by this integration and cannot be fixed by it. A solution was proposed and accepted as the best option to deal with the issue.

**Closed by nimroddolev** 2023-08-17 08:39 UTC
Labels: bug
