### ISSUE TITLE
mp3s directory is set to default "local" but it error not finding the files.

### ISSUE THREAD

**Issue by dmavromatis** [nimroddolev/chime_tts#126] opened 2024-05-01 02:19 UTC
### System Health details

2024-05-01 04:07:19.923 WARNING (MainThread) [custom_components.chime_tts] Unable to extract audio from file: "[Errno 2] No such file or directory: 'custom_components/chime_tts/mp3s/bells.mp3'"
2024-05-01 04:07:19.923 DEBUG (MainThread) [custom_components.chime_tts] - Generating new TTS audio with parameters:
2024-05-01 04:07:19.923 DEBUG (MainThread) [custom_components.chime_tts] * tts_platform = 'tts.elevenlabs_tts'
2024-05-01 04:07:19.923 DEBUG (MainThread) [custom_components.chime_tts] * message = 'Testy'
2024-05-01 04:07:19.923 DEBUG (MainThread) [custom_components.chime_tts] * cache = False
2024-05-01 04:07:19.923 DEBUG (MainThread) [custom_components.chime_tts] * language = None
2024-05-01 04:07:19.924 DEBUG (MainThread) [custom_components.chime_tts] * options = {}
2024-05-01 04:07:21.177 DEBUG (MainThread) [custom_components.chime_tts] ...TTS audio generated in 1.25s
2024-05-01 04:07:21.177 DEBUG (MainThread) [custom_components.chime_tts] - Saving mp3 file to folder: /config/www/chime_tts/...
2024-05-01 04:07:21.256 DEBUG (MainThread) [custom_components.chime_tts.helpers.filesystem] - File saved to path: /config/www/chime_tts/2z956sss.mp3
2024-05-01 04:07:21.256 DEBUG (MainThread) [custom_components.chime_tts] - Performing FFmpeg audio conversion...
2024-05-01 04:07:21.256 DEBUG (MainThread) [custom_components.chime_tts.helpers.helpers] Converting audio: "ffmpeg -i /config/www/chime_tts/2z956sss.mp3 -y -ac 2 -codec:a libmp3lame -b:a 48k -ar 24000 -write_xing 0 /config/www/chime_tts/2z956sss_converted.mp3"
2024-05-01 04:07:21.329 DEBUG (MainThread) [custom_components.chime_tts] ...FFmpeg audio conversion completed.
2024-05-01 04:07:21.432 DEBUG (MainThread) [custom_components.chime_tts] - Saving data to chime_tts storage:
2024-05-01 04:07:21.432 DEBUG (MainThread) [custom_components.chime_tts] - key: "9d0647b063251e03888ffce63d8a8a13afbdbf27e647af0e1653281c83468205"
2024-05-01 04:07:21.432 DEBUG (MainThread) [custom_components.chime_tts] - value: "{'public_path': '/config/www/chime_tts/2z956sss.mp3', 'audio_duration': 1.149, 'local_path': None}"
2024-05-01 04:07:21.434 DEBUG (MainThread) [custom_components.chime_tts] - Chime TTS audio generated:
2024-05-01 04:07:21.434 DEBUG (MainThread) [custom_components.chime_tts] - audio_duration = 1.68
2024-05-01 04:07:21.434 DEBUG (MainThread) [custom_components.chime_tts] - local_path = None
2024-05-01 04:07:21.434 DEBUG (MainThread) [custom_components.chime_tts] - public_path = "http://192.168.1.173:8123/local/chime_tts/2z956sss.mp3"
2024-05-01 04:07:21.434 DEBUG (MainThread) [custom_components.chime_tts] - media_content_id = None
2024-05-01 04:07:21.434 DEBUG (MainThread) [custom_components.chime_tts] *** Pre-Playback Actions ***
2024-05-01 04:07:21.434 DEBUG (MainThread) [custom_components.chime_tts] *** Chime TTS playback ***
2024-05-01 04:07:21.434 DEBUG (MainThread) [custom_components.chime_tts] 1 Alexa media player detected:
2024-05-01 04:07:21.434 DEBUG (MainThread) [custom_components.chime_tts] - media_player.rack_echo
2024-05-01 04:07:21.434 DEBUG (MainThread) [custom_components.chime_tts] Calling notify.alexa_media with data:
2024-05-01 04:07:21.434 DEBUG (MainThread) [custom_components.chime_tts] - message: <audio src="http://192.168.1.173:8123/local/chime_tts/2z956sss.mp3"/>
2024-05-01 04:07:21.434 DEBUG (MainThread) [custom_components.chime_tts] - data: {'type': 'tts'}
2024-05-01 04:07:21.434 DEBUG (MainThread) [custom_components.chime_tts] - target: ['media_player.rack_echo']
2024-05-01 04:07:21.435 DEBUG (MainThread) [custom_components.chime_tts] - Waiting 1.68s for audio playback to complete...
2024-05-01 04:07:23.116 DEBUG (MainThread) [custom_components.chime_tts.helpers.media_player] - Waiting until 1 media_player isn't playing...
2024-05-01 04:07:23.116 DEBUG (MainThread) [custom_components.chime_tts.helpers.media_player] ✔ media_player.rack_echo
2024-05-01 04:07:23.116 DEBUG (MainThread) [custom_components.chime_tts] ----- Chime TTS Say Completed in 3.2 s -----

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

ERROR: 

2024-05-01 04:07:19.922 DEBUG (MainThread) [custom_components.chime_tts] - Retrieving audio from path: "custom_components/chime_tts/mp3s/bells.mp3"...

However, when I look inside my docker :
/home/pi/docker/homeAssistant/data/custom_components/chime_tts/mp3s/bells.mp3
is there... what is that relative to?

I'm also not sure if the /media is correct... I don't have that folder, unless the "root" is some place I haven't checked.

<img width="586" alt="image" src="https://github.com/nimroddolev/chime_tts/assets/2848952/8a415110-eb17-4f00-9418-56728fc210eb">

### Reproduction steps

I just followed the instructions.

### Debug logs

```text
Posted above.
```

**Comment by nimroddolev** [comment] 2024-05-09 19:16
Hi @dmavromatis.

Thanks for reporting the issue.

I had added a potential fix in release v1.1.0-beta5. I would appreciate it if you could please upgrade and test to see if the issue is resolved.

To install the new beta version:
1. Open the <a href="https://my.home-assistant.io/redirect/hacs_repository/?owner=nimroddolev&repository=chime_tts&category=integration" title="Chime TTS HACS repository" target="_blank">Chime TTS repository in HACS</a>
1. Click on the `⋮` button in the top right
1. Select the `↻ Redownload` option
1. Enable the `Show beta versions` option (it may take a moment to update the list)
1. Select version `v1.1.0-beta5` from the updated version drop-down list
1. Restart Home Assistant

**Comment by LoznOz** [comment] 2024-05-10 12:29
Hi and thanks for your ongoing work on this
Its late night, so I'm posting a short note to advise that I too have been having this issue, have installed release v1.1.0-beta5 and unfortunately for me it is still failing to find or play either the built-in or my own few MP3 files. Whilst I am sincerely appreciative your work may I offer suggestion that the user interface (and file structure) for selecting any particular MP3 file is really confusing. when I first installed I was able to test successfully by selecting the included MP3 files. I then grabbed a few MP3 files I wanted to play with a bit further and thought Id put them in the directories so designated in the guide. After days I have never managed to get TTS Chime to find or play these. I'd imagined placing files in a directory and then pointing (via Configuration) TTS Chime to the directory they are in, expected to see (say) a drop down selection of the MP3 files contained in that directory, select the MP3 one wishes to use (in say an automation) and continue on with next steps. I don't mean to rant at all, rather suggest and provide feedback from a user that really wants to use this and help improve.
I'll try to get logs etc to you whan i can. 
thanks

**Comment by nimroddolev** [comment] 2024-05-11 14:34
Hi @LoznOz, I am sorry to hear the latest beta has not fixed the issue for you.

>unfortunately for me it is still failing to find or play either the built-in or my own few MP3 files.

When developing Chime TTS I develop and test on a docker instance and I also test with my HAOS (Raspberry Pi4) production instance. In both cases I am unable to reproduce your issue.
I based on feedback from other users I believe the problem is not widespread - so I would appreciate it if you could please share with me some more specifics of your setup in order to try and determine what the cause might be.
Additionally: could you please also provide full debug logs from v1.1.0-beta6?

>the user interface (and file structure) for selecting any particular MP3 file is really confusing...

Thanks for your feedback and suggestions. I understand that the experience of adding & selecting custom chimes is not perfect, and I agree that it would ideal if the chimes drop down list would reflect the contents of a specific folder.
Unfortunately I am not able to make this experience better due to how Home Assistant implements the list UI in services:
Each option in a the drop down list is hardcoded in the integration's code. You can technically modify the code to change or add new list options, however these changes will be erased when installing the next update of the integration.

The compromise I landed on was to include [5 custom chimes options in the list UI](https://nimroddolev.github.io/chime_tts/docs/documentation/say-service/#3-custom-chime-slots-for-the-chime-list-ui) which the user can set via the integration's configuration, which persist after updating.
Please also note that you can also specify both l[ocal paths to a custom chime files](https://nimroddolev.github.io/chime_tts/docs/documentation/say-service/#local-files) as well as [URLs to remote chime files](https://nimroddolev.github.io/chime_tts/docs/documentation/say-service/#external-audio-file-urls) instead of selecting from the dropdown list options.

**Comment by nimroddolev** [comment] 2024-05-13 05:47
Hi @dmavromatis and @LoznOz,

In beta5 I added additional code to determine the absolute path to the chime folder, as well as some additional debug log messages.

Please provide me with debug logs for either beta5 or beta6 when you get a chance.

**Comment by LoznOz** [comment] 2024-06-11 06:53
Thanks for following up. I've been away for a while and just ran a test with version v1.1.0-beta12.  Im running on fully updated HAOS, testing on Google nest Mini speakers and Google Hub Displays. TTS Speak via Piper works as expected. 

Chime TTS say does speak the TTS message part BUT I'm unable to get to play any custom mp3 audio files that Ive stored in what I think is the correct HA directory. In fact the first second or so of message is clipped / not played (like it started speaking the TTS words before sound began to be heard from speaker. I'll attached few debug logs of specific attempts (neither inbuilt nor custom MP3 sounds play, but the TTS message does). Hoping its something stupid i may have done or missed, but cause is eluding me .
appreciate your review of attached.
Thanks in anticipation

[Test local bells sound home-assistant_chime_tts_2024-06-11T06-46-02.563Z.log](https://github.com/user-attachments/files/15783445/Test.local.bells.sound.home-assistant_chime_tts_2024-06-11T06-46-02.563Z.log)
[home-assistant_chime_tts_2024-06-11T06-09-43.364Z.log](https://github.com/user-attachments/files/15783449/home-assistant_chime_tts_2024-06-11T06-09-43.364Z.log)
![My Config in HA Part 1](https://github.com/nimroddolev/chime_tts/assets/119017698/70bb8124-ce97-4c70-ba87-426593ec4cb1)
![My Config in HA Part 2](https://github.com/nimroddolev/chime_tts/assets/119017698/ffdbff27-5daf-4079-8bce-50708f6651b8)

**Comment by nimroddolev** [comment] 2024-06-11 13:56
Hi @LoznOz. Thanks for sharing your configuration and the debug log messages.

I don't see any issues with your configuration.

From the debug logs of your attempt to use a custom chime, Chime TTS could not find the file at the path you entered in your configuration:
```Custom chime not found at path: /config/www/sounds/tts/chimes/chime_tts/chimes/fasten_seatbelt.mp3``` 

I suggest you carefully check that this path is 100% correct. If it is, then it seems like Chime TTS cannot the file at this folder path for some reason. To confirm this, I suggest you copy the file to the default chimes folder, i.e: `/config/custom_components/chime_tts/mp3s/fasten_seatbelt.mp3` and use this path in place of `custom_chime_path_1` again with this path.

I think you should also check your `configuration.yaml` file, make sure you have the following under the `homeassistant` section:

```
homeassistant:
  media_dirs:
    local: /media
```

**Comment by nimroddolev** [comment] 2024-06-19 05:46
Hi @LoznOz, have you been able to resolve this issue?

**Comment by nimroddolev** [comment] 2024-06-25 06:30
I am closing this issue. If you still encounter this issue on the latest stable release, please open a new issue with debug log messages.

**Closed by nimroddolev** 2024-06-25 06:30 UTC
Labels: bug
