### ISSUE TITLE
Error after Updating  to 2024.9.0b1

### ISSUE THREAD

**Issue by def1149** [nimroddolev/chime_tts#183] opened 2024-08-29 17:19 UTC
## System Information

version | core-2024.9.0b1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.31-haos-raspi
arch | aarch64
timezone | America/Chicago
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.0
Stage | running
Available Repositories | 1389
Downloaded Repositories | 32

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 46

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | October 2, 2024 at 7:00 PM
relayer_connected | true
relayer_region | us-east-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | false
remote_server | us-east-1-9.ui.nabu.casa
certificate_status | ready
instance_id | 6db92b2b0db14ce798c80f31b021c265
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.1
-- | --
update_channel | beta
supervisor_version | supervisor-2024.08.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 229.2 GB
disk_used | 28.0 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | yellow
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (18.0.0), Home Assistant Google Drive Backup (0.112.1), Z-Wave JS (0.6.2), Network UPS Tools (0.13.1), SQLite Web (4.2.0), Piper (1.5.2), AWNET to HASS (1.1.2), Mosquitto broker (6.4.1), MQTT Explorer (browser-1.0.3), Frigate Proxy (1.5), Glances (0.21.1), ESPHome (2024.8.1), File editor (5.8.0), Duck DNS (1.18.0), Studio Code Server (5.15.0), Node-RED (18.0.5)

</details>

<details><summary>keymaster</summary>

zwave_integration | zwave_js
-- | --
network_status | on

</details>

<details><summary>Dashboards</summary>

dashboards | 9
-- | --
resources | 21
views | 19
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | August 20, 2024 at 4:11 AM
-- | --
current_recorder_run | August 29, 2024 at 12:09 PM
estimated_db_size | 644.23 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/nimroddolev/chime_tts/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Errors in HA Log 

### Reproduction steps

Update to 2024.9.0b1

### Debug logs

```text
Logger: py.warnings
Source: custom_components/chime_tts/__init__.py:9
integration: Chime TTS (documentation, issues)
First occurred: 12:09:18 PM (4 occurrences)
Last logged: 12:09:18 PM

/usr/local/lib/python3.12/site-packages/pydub/utils.py:300: SyntaxWarning: invalid escape sequence '\(' m = re.match('([su]([0-9]{1,2})p?) \(([0-9]{1,2}) bit\)$', token)
/usr/local/lib/python3.12/site-packages/pydub/utils.py:301: SyntaxWarning: invalid escape sequence '\(' m2 = re.match('([su]([0-9]{1,2})p?)( \(default\))?$', token)
/usr/local/lib/python3.12/site-packages/pydub/utils.py:310: SyntaxWarning: invalid escape sequence '\(' elif re.match('(flt)p?( \(default\))?$', token):
/usr/local/lib/python3.12/site-packages/pydub/utils.py:314: SyntaxWarning: invalid escape sequence '\(' elif re.match('(dbl)p?( \(default\))?$', token):
```

**Comment by JonLaliberte** [comment] 2024-09-10 14:24
Yep, seeing this as well.

**Comment by JonLaliberte** [comment] 2024-09-10 14:36
@nimroddolev 
When I set the Chime Path to a default which has a space in it, for example "Bells 2" or "Ding Dong", it fails. If I set it to something without a space, it works.

My guess is this is related?

**Comment by def1149** [comment] 2024-09-10 14:48
Makes sense as the ONLY Chime I use is Bells 2

**Comment by nimroddolev** [comment] 2024-09-16 14:09
Hey @def1149 & @JonLaliberte. Sorry you've had this issue. I have tested on v2024.9.0 and v2024.9.1 and was unable to reproduce your issue. Could it be that the issue was related to an issue in the HA beta version?
Can you please test and confirm for me whether the issue persists for you past the beta?
If so, please include your YAML for the action call.

**Comment by JonLaliberte** [comment] 2024-09-16 15:15
@nimroddolev 
Sorry, I didn't notice that the OP was on a beta. I was never on HA beta though (I usually don't update until at least one point release or more as I depend on a few things working).

I was on then, and now 2024.9.1.

Anyway, I tested it just now and using "Bells 2" and "Ding Dong" are working fine now without any changes. When I tested last week I was consistently having it fail with that "invalid escape sequence" error on these, but when using sounds without spaces it was working. Maybe it was all a coincidence and a HA restart in the meantime fixed something.

**Comment by def1149** [comment] 2024-09-17 22:44
No problems now .. .thanks

**Comment by nimroddolev** [comment] 2024-09-18 06:01
Great, closing the issue 👍

**Closed by nimroddolev** 2024-09-18 06:01 UTC

**Comment by 26tajeen** [comment] 2025-05-04 18:37
https://github.com/nimroddolev/chime_tts/issues/270
